name: pypx800v5 Python API Client

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Create Python virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U "pip<20.3" setuptools
          pip install -r requirements.txt
      - uses: psf/black@stable
        with:
          options: "pypx800v5 --check"
      - uses: jpetrucciani/mypy-check@master
        with:
          path: pypx800v5
          mypy_flags: --config-file mypy.ini
