name: pypx800v5 Python API Client

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          black_args: "pypx800v5 --check"
      - uses: jpetrucciani/mypy-check@master
        with:
          path: pypx800v5
